---
# tasks file for roles/accept_vpc_peering
- name: Accept peering connection
  ec2_vpc_peer:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: ap-northeast-1
    peering_id: "{{ vpc_peer.peering_id }}"
    state: accept
  register: action_peer
#- name: Editing DNS settings on VPC peering
 # command: aws ec2 modify-vpc-peering-connection-options --vpc-peering-connection-id "{{ vpc_peer.peering_id }}" --requester-peering-connection-options '{"AllowDnsResolutionFromRemoteVpc":true}' --accepter-peering-connection-options '{"AllowDnsResolutionFromRemoteVpc":true}' --region "{{region}}"
