---
- hosts: webserver
  vars_files:
  - ../variables_file.yml
  tasks:
  - name: Creating AppServer2
    include_role:
     name: ../roles/ec2_app
    vars:
     instance_name: "{{app_instance_name2}}"
     ec2_type: "{{App_ec2_type}}"
     ec2_image: "{{App_ec2_image}}"
     ec2_name: appserver2
     ec2_subnet_id: "{{appsubnet2.subnet.id}}"
     myip: 20.0.4.150
     sg: "{{app_sg.group_name}}"
     public_ip: no
